version: '3.8'

services:
  app:
    build: .
    container_name: app_container
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - db
    environment:
      - MYSQL_HOST=db
      - MYSQL_DATABASE=clinica
      - MYSQL_USER=root
      - MYSQL_PASSWORD=admin
    volumes:
      - .:/var/www/html
      # Montar los certificados SSL
      - /etc/letsencrypt/live/clinicagt.shop:/etc/letsencrypt/live/clinicagt.shop:ro
      - /etc/letsencrypt/archive/clinicagt.shop:/etc/letsencrypt/archive/clinicagt.shop:ro

  db:
    image: mysql:8.0
    container_name: db_container
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: clinica
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
      TZ: America/Guatemala
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
